apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hello-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-rhtap 
  name: hello-rhtap
  namespace: pkumari
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hello-rhtap 
